title: "cjunior's blog"
description: "cjunior's blog"
#baseurl: "/jekyll-theme-console-demo-dark"
url: "https://officialcjunior.github.io"

header_pages:
  - index.md
  - blog.md
  - reversing.md
  - notes.md
  - about.md

style: hacker

footer: 'subscribe to my <a href="https://officialcjunior.github.io/feed.xml">RSS feed</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
