title: "cjunior's blog"
description: "cjunior's blog"
#baseurl: "/jekyll-theme-console-demo-dark"
url: "https://officialcjunior.github.io"

header_pages:
  - index.md
  - blog.md
  - reversing.md
  - notes.md
  - about.md

style: hacker

footer: 'follow me on <a href="https://oldbytes.space/@officialcjunior">Mastodon</a> <3'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
