baseurl: "/"
languageCode: "en-us"
title: "Aswin's blog"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  blog: "/blog/:slug/"

menu:
  main:
    - name: home
      url: ""
      weight: 1
    - name: projects
      url: "projects/"
      weight: 2
    - name: about
      url: "about/"
      weight: 3

params:
  description: "Aswin's blog"
  footer: "Aswin's blog      <br/>  [subscribe](/index.xml)"

markup:
  goldmark:
    renderer:
      unsafe: true
